version: '3.5'

services:

    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq
   
    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        ports:
            - "1883:1883"
        expose:
            - 1883
        depends_on:
            - vernemq
       
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/ 
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        command: >
            sh -c "sleep 15 && python3 manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - streamer
            - db
                
        # restart: on-failure
volumes:
  postgres_data:


