version: '3.5'

services:

    vernemq:
        # network_mode: host
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq
   
    streamer:
        # network_mode: host
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        ports:
            - "1883:1883"
        depends_on:
            - vernemq
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        command: >
            sh -c "python3 manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - vernemq
        restart: on-failure


