# Generated by Django 4.1.3 on 2022-11-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_id', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_id'], name='stocks_stoc_stock_i_c752ea_idx'),
        ),
    ]
