# Generated by Django 4.1.3 on 2022-12-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockstream',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_stream', to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_id'], name='stocks_stoc_stock_i_c752ea_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['name'], name='stocks_stoc_name_6f3be2_idx'),
        ),
        migrations.AddField(
            model_name='pendingorders',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pending_stock', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='pendingorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockstream',
            index=models.Index(fields=['stock_id', 'timestamp'], name='stocks_stoc_stock_i_0020bc_idx'),
        ),
    ]
