# Generated by Django 4.1.3 on 2022-12-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['name'], name='stocks_stoc_name_6f3be2_idx'),
        ),
        migrations.AddField(
            model_name='stockstream',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_stream', to='stocks.stock'),
        ),
    ]
