# Generated by Django 4.1.3 on 2022-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockstream_stock_stocks_stoc_name_6f3be2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockstream',
            index=models.Index(fields=['stock_id', 'timestamp'], name='stocks_stoc_stock_i_0020bc_idx'),
        ),
    ]
